# ٭ Exercices

## Questions

- Quelles sont les erreurs du test consistant à toujours accepter l'hypothèse nulle ?
- Quelles sont les erreurs du test consistant à toujours refuser l'hypothèse nulle ?
- Montrer que la distance en variation totale entre deux mesures de densités $p,q$ peut aussi s'écrire $\int(p/q-1)_+ \mathrm{d}p$. 
- Montrer que si $\mathrm{d}_{\mathrm{KL}}(P_n \mid Q) \to 0$, alors $P_n$ converge en loi vers $Q$. 
- Calculer la distance en variation totale entre deux lois de Bernoulli de paramètres respectifs $p$ et $q$.
- Calculer la distance en variation totale entre une loi $\mathrm{Bin}(n,p)$ et une loi $N(\mu,\sigma^2)$. 
- Soient $P,Q$ deux mesures. Montrer que $\dkl(P^{\otimes n} \mid Q^{\otimes n}) = n \dkl(P \mid Q)$. 

## Tests élémentaires

Pour tous les cas suivants, il faut savoir réaliser rapidement un test puissant, voire même optimal au sens qu'il vous plaira. 

- Tester $\mu = \mu_0$ contre $\mu = \mu_1$ dans un échantillon $N(\mu, \sigma^2)$ lorsque $\mu$ est connu. 
- Même question lorsque $\mu$ est inconnu. 
- Soient $X_1, \dotsc, X_n$ un échantillon iid $N(\mu_1,\sigma_1^2)$ et $Y_1, \dotsc, Y_m$ ($m$ et $n$ ne sont pas forcément égaux) un échantillon iid de loi $N(\mu_2,\sigma_2^2)$. Tester $\sigma_1 = \sigma_2$ lorsque $\mu_1$ et $\mu_2$ sont connues. 
- Même question lorsque $\mu_1$ et $\mu_2$ ne sont pas connues. 
- Donner la forme d'un test sur la valeur de $p$ pour une réalisation d'une loi $\mathrm{Bin}(n,p)$ et calculer son niveau asymptotique quand $n\to\infty$. 
- Donner la forme d'un test sur la valeur de $\lambda$ dans un échantillon de $n$ variables aléatoires de Poisson de paramètre $\lambda$. 
  
## Exercices

:::{#exr-testchideux}

Soient $X_1, \dotsc, X_n$ des variables indépendantes de loi $\chi_2(p)$. On cherche à tester l'hypothèse nulle $p=1$ contre l'hypothèse alternative $p=2$. 

1. Écrire la forme de la région de rejet des tests de rapport de vraisemblance. 
2. Essayer de calculer le niveau de ce test ; si ce n'est pas possible, essayer de le borner. 

:::

:::{#exr-testvar}

Soient $X_1, \dotsc, X_n$ des variables indépendantes de loi $N(0,\sigma^2)$. Proposer un test de niveau $\alpha$ de l'hypothèse $\sigma^2=1$ contre l'hypothèse $\sigma^2 = 1+\varepsilon$, et estimer sa puissance. Comment varie-t-elle en fonction de $n$ et de $\varepsilon$ ?

:::

:::{#exr-testrandom}

Soient $X_1, \dotsc, X_n$ des variables indépendantes de même loi $P$. On cherche à tester l'hypothèse nulle $P = N(0,1)$ contre l'hypothèse alternative $P = \mathscr{T}(n)$. 

1. Donner le test optimal au sens de l'affinité. 
2. Donner un autre test, de niveau $1-\alpha$, et calculer sa puissance. 
3. Comparer ces deux tests, en particulier dans le régime où $n$ est grand. 
:::

:::{#exr-samplecomplexity}

Montrer que le nombre de lancers nécessaire pour distinguer une pièce équilibrée $(p=1/2)$ d'une pièce légèrement déséquilibrée ($p_1 = 1/2 + \varepsilon$) est d'ordre $1/\varepsilon^2$. 

:::


:::{#exr-bintest}

On note $p$ la probabilité qu'un enfant né vivant soit un garçon. On suppose que les enfants sont de sexe indépendants, et que cette probabilité est la même pour toutes les grossesses.

1. Il y a eu en France métropolitaine en 2015 $n=760\,421$ naissances.
, dont $389\,181$ garçons. Tester l'hypothèse $p=\frac12$ contre l'alternative pertinente.
1. En 1920, il y a eu $838\,137$ naissances dont $432\,044$ garçons. Tester l'hypothèse $p_{2015}=p_{1920}$.

:::


:::{#exr-testsdivers}


Soient $X_1, \dotsc, X_n$ i.i.d de loi $N(\theta,1)$, où $\theta$ est un paramètre réel. 

1. Donner un intervalle de confiance pour $\theta$ au niveau de risque $5\%$ de la forme $[\hat{\theta}_n, +\infty[$. 
2. En déduire un test de niveau $5\%$ pour les hypothèses $H_0: \theta = 0$ et $H_1: \theta >0$.
3. Donner le modèle de l'expérience statistique. Donner l'expression du test de rapport de vraisemblance $T$ pour les hypothèses $H_0: \theta =0$ et $H_1: \theta = \mu$, où $\mu >0$. Quel test retrouve-t-on? 
4. Construire le test de rapport de vraisemblance au niveau $5\%$ pour les hypothèses $H_0: \theta = 0$ et $H_1: \theta >0$.

:::

:::{#exr-testunif}


## Test sur des lois uniformes 

On se donne $X_1, \dots, X_n$ iid de loi $\mathscr{U}(0,\theta)$, et on note $M_n = \max_{j=1, \dots, n} X_i$.

1. Écrire la fonction de répartition de $M_n$, puis en déduire un test $T$ de niveau $1-\alpha$ pour les hypothèses $H_0: \theta = 1$ contre $H_1: \theta < 1$.
2. Donner le test du rapport de vraisemblance pour pour les hypothèses $H_0: \theta = 1$ contre $H_1: \theta = \theta_0$, où $\theta_0<1$. Calculer sa puissance. 
3. On cherche à tester $H_0: \theta = 1$ contre $H_1: \theta < 1$. Comme la seconde hypothèse est composite, on ne peut pas directement appliquer le test du rapport de vraisemblance ; à la place, on utilise un test du *maximum* de vraisemblance, qui est de la forme 
   $$ \frac{\sup_{\theta < 1}\rho_\theta(x_1, \dotsc, x_n)}{\rho_1(x_1, \dotsc, x_n)} > z$$
   où $\rho_\theta$ est la densité d'un échantillon iid de lois $\mathscr{U}[0,\theta]$. Calculer le supremum dans cette expression, et en déduire la région de rejet. 
4. Montrer que la puissance de $T$ vaut $1-\alpha$.
5. En utilisant la même technique, construire le test du rapport de maximum de vraisemblance pour pour les hypothèses $H_0: \theta = 1$ contre $H_1: \theta>1$, noté $T'$, au niveau $1-\alpha$. Calculer sa puissance. 
6. Donner un test de niveau $1-\alpha$ pour $H_0: \theta = 1$ contre $H_1: \theta>1$, plus puissant que $T'$ pour n'importe quel $\theta >1$. 

:::

:::{#exr-binomtest}

Une réalisation d'une variable aléatoire $X \sim \mathrm{Bin}(20,p)$ donne $X = 8$. 

1. Proposer un test du rapport de vraisemblance de l'hypothèse nulle $p=p_0=1/2$ contre l'hypothèse alternative $p=p_1=1/3$. Donner l'expression de la $p$-valeur du test.
2. On tire des variables aléatoires iid de Bernoulli jusqu'à obtenir 8 succès. Écrire la loi de probabilité du nombre de lancers $N$.
3. Il se trouve que le nombre de lancers nécessaires pour cela était $N=20$.  Proposer un test du rapport de vraisemblance de l'hypothèse nulle $p=p_0=1/2$ contre l'hypothèse alternative $p=p_1=1/3$. Donner l'expression de la $p$-valeur du test. 
4. Pourquoi les deux $p$-valeurs sont-elles différentes, alors que les deux tests sont identiques ?

:::


:::{#exr-testdé}

## Test d'adéquation du $\chi_2$

On lance $60$ fois un dé et on obtient les résultats suivants :

| **Face $k$** | 1 | 2 | 3 | 4 | 5 | 6 |
|---------|:-:|:-:|:-:|:-:|:-:|:-:|
| **Effectif $N_k$**      | 10   |    13 |   8   | 12 | 9 | 8 |



Le dé est-il bien équilibré ? À titre indicatif, le quantile d'une loi $\chi^2(5)$ d'ordre $95\%$ est $11.07$.

:::

:::{#exr-testind}

## Test d'indépendance du $\chi_2$

On cherche à savoir si les variables « être riche » et « être heureux » sont indépendantes. On interroge un grand échantillon de personnes à ce sujet, et l'on récolte les données suivantes : 

| | riche | pauvre | 
|-|-|-|-|
| **heureux** |344 | 700|
| **triste**| 257| 705 | 


L'argent fait-il le bonheur ?

:::

# Annales de partiel

Je ne garantis pas que les notations et les concepts utilisés dans ces annales soient en phase avec le cours de cette année !

- [Partiel 2020](/pdfs/CC1.pdf) et [sa correction](/pdfs/Corrige_CC1.pdf)

- [Examen 2020](/pdfs/ExoExam.pdf) ; ne pas regarder le deuxième exercice. 

- [Partiel 2023](/pdfs/Partiel2023.pdf) et [sa correction](/pdfs/Partiel2023Corrige.pdf)




