# Références {.unnumbered}

- [Statistics done Wrong](https://www.statisticsdonewrong.com/)
- [The earth is round (p<.05)](https://www.sjsu.edu/faculty/gerstman/misc/Cohen1994.pdf)
- [The Epic Story of Maximum Likelihood](https://arxiv.org/abs/0804.2996)
- [Statistiques mathématiques en action](https://www.deboecksuperieur.com/ouvrage/9782311007206-statistique-mathematique-en-action), pour ceux qui vont passer l'agrégation. 
- [Introduction à l'économétrie](https://www.eyrolles.com/Entreprise/Livre/introduction-a-l-econometrie-9782707613981/) de Brigitte Dormont est un excellent livre, écrit en français, sur les modèles linéaires. 
- En anglais, la référence sur les modèles linéaires est [Econometric analysis](https://www.pearson.fr/book/?gcoi=27440100285130) de Greene. 
- [Méthodes statistiques](https://www.eyrolles.com/Sciences/Livre/methodes-statistiques-9782717848595/) de Philippe Tassi est un bon livre général. 
- [All of statistics](https://egrcc.github.io/docs/math/all-of-statistics.pdf) de Larry Wasserman est un ouvrage de référence. 
- [Le cours de Stéphane Mallat au Collège de France](https://www.college-de-france.fr/fr/agenda/cours/information-et-complexite) qui est plus général, mais qui reprend tous les concepts. 
- [L'article original de Ronald Fisher](/docs/fisher.pdf) de 1922 (et pas 1935 comme j'ai dit en cours), qui pose *toutes* les bases de la statistique moderne. 
- [Computer age statistical inference](https://hastie.su.domains/CASI_files/PDF/casi.pdf) de Bradley Efron et Trevor Hastie n'est pas un livre de mathématiques, mais c'est le meilleur livre qui présente les idées et les algorithmes des statistiques avec un point de vue moderne. 
- [Elements of information theory](https://onlinelibrary.wiley.com/doi/book/10.1002/047174882X), une référence sur la théorie de l'information. 