<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="fr" xml:lang="fr"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.3.450">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>Statistiques Fondamentales - 4&nbsp; Intervalles de confiance</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<link href="./ch4.html" rel="next">
<link href="./ch2_ex.html" rel="prev">
<script src="site_libs/quarto-html/quarto.js"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" class="quarto-color-scheme" id="quarto-text-highlighting-styles">
<link href="site_libs/quarto-html/quarto-syntax-highlighting-dark.css" rel="prefetch" class="quarto-color-scheme quarto-color-alternate" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" class="quarto-color-scheme" id="quarto-bootstrap" data-mode="light">
<link href="site_libs/bootstrap/bootstrap-dark.min.css" rel="prefetch" class="quarto-color-scheme quarto-color-alternate" id="quarto-bootstrap" data-mode="dark">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 20,
  "language": {
    "search-no-results-text": "Pas de résultats",
    "search-matching-documents-text": "documents trouvés",
    "search-copy-link-title": "Copier le lien vers la recherche",
    "search-hide-matches-text": "Cacher les correspondances additionnelles",
    "search-more-match-text": "correspondance de plus dans ce document",
    "search-more-matches-text": "correspondances de plus dans ce document",
    "search-clear-button-title": "Effacer",
    "search-detached-cancel-button-title": "Annuler",
    "search-submit-button-title": "Envoyer",
    "search-label": "Recherche"
  }
}</script>

  <script src="https://polyfill.io/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<link rel="stylesheet" href="styles.css">
</head>

<body class="nav-sidebar docked">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar,#quarto-sidebar-glass" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Basculer la barre latérale" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
      <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./ch3.html"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Intervalles de confiance</span></a></li></ol></nav>
      <a class="flex-grow-1" role="button" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar,#quarto-sidebar-glass" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Basculer la barre latérale" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
      </a>
      <button type="button" class="btn quarto-search-button" aria-label="" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal sidebar-navigation docked overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header sidebar-header-stacked">
      <a href="./index.html" class="sidebar-logo-link">
      <img src="./images/logoUP.png" alt="" class="sidebar-logo py-0 d-lg-inline d-none">
      </a>
    <div class="sidebar-title mb-0 py-0">
      <a href="./">Statistiques Fondamentales</a> 
        <div class="sidebar-tools-main tools-wide">
    <a href="https://github.com/statsfonda/site" rel="" title="Source Code" class="quarto-navigation-tool px-1" aria-label="Source Code"><i class="bi bi-github"></i></a>
    <a href="./Statistiques-Fondamentales.pdf" rel="" title="Download PDF" class="quarto-navigation-tool px-1" aria-label="Download PDF"><i class="bi bi-file-pdf"></i></a>
  <a href="" class="quarto-color-scheme-toggle quarto-navigation-tool  px-1" onclick="window.quartoToggleColorScheme(); return false;" title="Basculer le mode sombre"><i class="bi"></i></a>
</div>
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Recherche"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Organisation</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./ch1.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Introduction</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./ch2.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Estimation de paramètre</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./ch2_ex.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Exercices</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./ch3.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Intervalles de confiance</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./ch4.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Test d’hypothèse</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./ch5.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Économétrie</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./ch6.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Théorie de l’information</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./ch7.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">Estimation de densité</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./references.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Et après ?</span></a>
  </div>
</li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar,#quarto-sidebar-glass"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table des matières</h2>
   
  <ul>
  <li><a href="#principe" id="toc-principe" class="nav-link active" data-scroll-target="#principe"><span class="header-section-number">4.1</span> Principe</a></li>
  <li><a href="#exemples-gaussiens" id="toc-exemples-gaussiens" class="nav-link" data-scroll-target="#exemples-gaussiens"><span class="header-section-number">4.2</span> Exemples gaussiens</a>
  <ul class="collapse">
  <li><a href="#estimation-de-mu" id="toc-estimation-de-mu" class="nav-link" data-scroll-target="#estimation-de-mu"><span class="header-section-number">4.2.1</span> Estimation de <span class="math inline">\(\mu\)</span></a></li>
  <li><a href="#estimation-de-sigma" id="toc-estimation-de-sigma" class="nav-link" data-scroll-target="#estimation-de-sigma"><span class="header-section-number">4.2.2</span> Estimation de <span class="math inline">\(\sigma\)</span></a></li>
  </ul></li>
  <li><a href="#exemples-asymptotiques" id="toc-exemples-asymptotiques" class="nav-link" data-scroll-target="#exemples-asymptotiques"><span class="header-section-number">4.3</span> Exemples asymptotiques</a></li>
  <li><a href="#outils-pour-construire-des-intervalles-de-confiance" id="toc-outils-pour-construire-des-intervalles-de-confiance" class="nav-link" data-scroll-target="#outils-pour-construire-des-intervalles-de-confiance"><span class="header-section-number">4.4</span> Outils pour construire des intervalles de confiance</a>
  <ul class="collapse">
  <li><a href="#quantiles" id="toc-quantiles" class="nav-link" data-scroll-target="#quantiles"><span class="header-section-number">4.4.1</span> Quantiles</a></li>
  <li><a href="#inégalités-de-concentration" id="toc-inégalités-de-concentration" class="nav-link" data-scroll-target="#inégalités-de-concentration"><span class="header-section-number">4.4.2</span> Inégalités de concentration</a></li>
  </ul></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Intervalles de confiance</span></h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  

</header>

<section id="principe" class="level2" data-number="4.1">
<h2 data-number="4.1" class="anchored" data-anchor-id="principe"><span class="header-section-number">4.1</span> Principe</h2>
<p>Dans un modèle statistique, l’estimation du paramètre d’intérêt <span class="math inline">\(\theta\)</span> par intervalles de confiance consiste à spécifier un intervalle calculable à partir des données, et qui contient <span class="math inline">\(\theta\)</span> avec grande probabilité : en d’autres termes, une <em>région de confiance</em> pour <span class="math inline">\(\theta\)</span>.</p>
<p>Pour simplifier, on supposera d’abord que <span class="math inline">\(\theta\)</span> est un paramètre réel.</p>
<div id="def-ic" class="theorem definition">
<p><span class="theorem-title"><strong>Définition 4.1 (intervalle de confiance) </strong></span>Un intervalle de confiance de niveau <span class="math inline">\(1-\alpha\)</span> est un intervalle <span class="math inline">\(I = [A,B]\)</span> dont les bornes <span class="math inline">\(A,B\)</span> sont des statistiques, et tel que pour tout <span class="math inline">\(\theta\)</span>, <span class="math display">\[P_\theta(\theta \in I) \geqslant 1 - \alpha.\]</span> Un intervalle de confiance de niveau asymptotique <span class="math inline">\(1-\alpha\)</span> est une <em>suite</em> d’intervalles <span class="math inline">\(I_n = [A_n,B_n]\)</span> dont les bornes <span class="math inline">\(A_n,B_n\)</span> sont des statistiques, et tels que pour tout <span class="math inline">\(n\)</span>, <span class="math display">\[ P_\theta(\theta \in I_n) \geqslant 1 - \alpha.\]</span></p>
</div>
<p>Le terme « niveau » désigne <span class="math inline">\(1-\alpha\)</span> ; la vocation de ce nombre est d’être proche de 1, typiquement 99%. Le nombre <span class="math inline">\(\alpha\)</span> est parfois appelé « erreur » ou « marge d’erreur » ; la vocation de ce nombre est d’être proche de zéro, typiquement 1%.</p>
<p>Il n’y a rien d’autre à savoir sur les intervalles de confiance ; tout l’art de la chose consiste à savoir les construire. Commençons par trois exemples essentiels à plusieurs titres.</p>
</section>
<section id="exemples-gaussiens" class="level2" data-number="4.2">
<h2 data-number="4.2" class="anchored" data-anchor-id="exemples-gaussiens"><span class="header-section-number">4.2</span> Exemples gaussiens</h2>
<p>On dispose de variables aléatoires <span class="math inline">\(X_1, \dotsc, X_n\)</span> gaussiennes de loi <span class="math inline">\(N(\mu, \sigma^2)\)</span>. On va donner des intervalles de confiance pour l’estimation des paramètres <span class="math inline">\(\mu\)</span> et <span class="math inline">\(\sigma\)</span> dans plusieurs cas de figure. Le moment est idéal pour rappeler l’existence et le calcul des <em>quantiles</em> d’une loi — voir ci dessous.</p>
<section id="estimation-de-mu" class="level3" data-number="4.2.1">
<h3 data-number="4.2.1" class="anchored" data-anchor-id="estimation-de-mu"><span class="header-section-number">4.2.1</span> Estimation de <span class="math inline">\(\mu\)</span></h3>
<p><strong>Lorsque <span class="math inline">\(\sigma\)</span> est connue. </strong></p>
<p>Nous avons déjà vu que la moyenne empirique <span class="math inline">\(\bar{X}_n\)</span> est un estimateur sans biais de <span class="math inline">\(\mu\)</span>. Or, nous savons aussi la loi <em>exacte</em> de <span class="math inline">\(\bar{X}_n\)</span>, qui est <span class="math inline">\(N(\mu, \sigma^2/n)\)</span>. Autrement dit, <span id="eq-pivg"><span class="math display">\[\frac{\sqrt{n}}{\sigma}(\bar{X}_n - \mu) \sim N(0,1). \tag{4.1}\]</span></span></p>
<p>Si l’on se donne une marge d’erreur <span class="math inline">\(\alpha = 1\%\)</span>, alors <span class="math display">\[ \mathbb{P}( (\sqrt{n}/\sigma)|\bar{X}_n - \mu| &gt; z_{0.99}) = 1\%\]</span> où <span class="math inline">\(z_{0.99} \approx 2.32\)</span>. Or, <span id="eq-piv1"><span class="math display">\[ \frac{\sqrt{n}}{\sigma}|\bar{X}_n - \mu| &gt; z_{0.99} \tag{4.2}\]</span></span> est équivalent à <span id="eq-piv2"><span class="math display">\[ \bar{X}_n - \frac{z_{0.99}\sigma}{\sqrt{n}} \leqslant \mu \leqslant \bar{X}_n + \frac{z_{0.99}\sigma}{\sqrt{n}}. \tag{4.3}\]</span></span> Le passage de <a href="#eq-piv1">Équation&nbsp;<span>4.2</span></a> à <a href="#eq-piv2">Équation&nbsp;<span>4.3</span></a> est souvent appelé <em>pivot</em>.</p>
<p>Nous avons donc les deux bornes de notre intervalle de confiance : <span class="math display">\[ A = \bar{X}_n - \frac{z_{0.99}\sigma}{\sqrt{n}}\]</span> <span class="math display">\[ B = \bar{X}_n + \frac{z_{0.99}\sigma}{\sqrt{n}} .\]</span> Ces deux quantités sont bien des statistiques, car <span class="math inline">\(\sigma\)</span> est connu. De plus, nous venons de montrer que <span class="math inline">\(P_\mu(\mu \in [A,B]) = 99\%\)</span>. Ici, le choix de la marge d’erreur <span class="math inline">\(\alpha = 1\%\)</span> ne jouait aucun rôle particulier ; ainsi, un intervalle de confiance de niveau <span class="math inline">\(1-\alpha\)</span> pour l’estimation de <span class="math inline">\(\mu\)</span> est donné par <span class="math display">\[\left[\bar{X}_n - \frac{z_{1-\alpha}\sigma}{\sqrt{n}}~~;~~\bar{X}_n + \frac{z_{1-\alpha}\sigma}{\sqrt{n}} \right].\]</span></p>
<p><strong>Exercice.</strong> Montrer que cet intervalle de confiance est plus grand possible.</p>
<p><strong>Lorsque <span class="math inline">\(\sigma\)</span> est inconnue. </strong></p>
<p>Lorsque <span class="math inline">\(\sigma\)</span> n’est pas connu, les bornes <span class="math inline">\(A,B\)</span> ci-dessus ne sont pas des statistiques, car elles dépendent de <span class="math inline">\(\sigma\)</span>. Heureusement, on peut estimer <span class="math inline">\(\sigma\)</span> sans biais via l’estimateur <span class="math display">\[ \hat{\sigma}_n^2 = \frac{1}{n-1}\sum_{i=1}^n (X_i - \bar{X}_n)^2.\]</span> Que se passe-t-il si, dans la statistique <a href="#eq-pivg">Équation&nbsp;<span>4.1</span></a>, on remplace <span class="math inline">\(\sigma\)</span> par son estimation <span class="math inline">\(\hat{\sigma}_n^2\)</span> ? La loi n’est plus gaussienne. Il se trouve que la loi de <span id="eq-pivst"><span class="math display">\[\frac{\sqrt{n}}{\hat{\sigma}^2_n}(\bar{X}_n - \mu) \tag{4.4}\]</span></span> s’appelle <a href="https://fr.wikipedia.org/wiki/Loi_de_Student"><em>loi de Student</em></a> à <span class="math inline">\(n-1\)</span> paramètres de liberté. Cette loi de référence est bien connue ; sa densité est <span class="math display">\[ \rho_k(x) = \frac{1}{Z_k}\left(\frac{1}{1+\frac{x^2}{k}}\right)^{\frac{k+1}{2}}, \]</span> où <span class="math inline">\(Z_k\)</span> est la constante de normalisation donnée par <span class="math display">\[ Z_k = \sqrt{k\pi}\frac{\Gamma((k+1)/2)}{\Gamma(k/2)}.\]</span> Ses quantiles ont également été calculés avec une grande précision. On notera <span class="math inline">\(t_{k,\alpha}\)</span> le quantile symétrique de niveau <span class="math inline">\(\alpha\)</span> d’une loi de Student de paramètre <span class="math inline">\(k\)</span>. Alors, <span class="math display">\[ P_{\mu, \sigma^2}(|T_n|&gt; t_{n-1,\alpha})\leqslant \alpha .\]</span> Par le même raisonnement que tout à l’heure, l’inégalité <span class="math display">\[ \left|\frac{\sqrt{n}}{\hat{\sigma}^2_n}(\bar{X}_n - \mu)\right| &gt; t_{n-1,\alpha}\]</span> est équivalente à <span class="math display">\[ \bar{X}_n - \frac{t_{n-1,\alpha}\hat{\sigma}^2_n}{\sqrt{n}} \leqslant \mu \leqslant \bar{X}_n + \frac{t_{n-1,\alpha}\hat{\sigma}^2_n}{\sqrt{n}}.\]</span> et les deux côtés de ces inégalités sont des statistiques;&nbsp;en les notant <span class="math inline">\(A,B\)</span>, on a bien trouvé un intervalle de confiance de niveau <span class="math inline">\(\alpha\)</span>, c’est-à-dire tel que <span class="math inline">\(P_{\mu,\sigma^2}(\mu \in [A,B]) = \alpha\)</span>.</p>
<div id="thm-icg" class="theorem">
<p><span class="theorem-title"><strong>Théorème 4.1 (Intervalle de Student) </strong></span>Un intervalle de confiance de niveau <span class="math inline">\(1-\alpha\)</span> pour l’estimation de <span class="math inline">\(\mu\)</span> lorsque <span class="math inline">\(\sigma\)</span> n’est pas connue est donné par</p>
<p><span class="math display">\[\left[\bar{X}_n - \frac{t_{1-\alpha}\hat{\sigma}_n}{\sqrt{n}}~~;~~\bar{X}_n + \frac{t_{1-\alpha}\hat{\sigma}_n}{\sqrt{n}} \right].\]</span></p>
</div>
</section>
<section id="estimation-de-sigma" class="level3" data-number="4.2.2">
<h3 data-number="4.2.2" class="anchored" data-anchor-id="estimation-de-sigma"><span class="header-section-number">4.2.2</span> Estimation de <span class="math inline">\(\sigma\)</span></h3>
<p>Supposons maintenant qu’on désire estimer la variance <span class="math inline">\(\sigma^2\)</span>.</p>
<p><strong>Lorsque <span class="math inline">\(\mu\)</span> est connue.</strong></p>
<p>En supposant que <span class="math inline">\(\mu\)</span> est connue, l’estimateur des moments le plus naturel pour estimer <span class="math inline">\(\sigma^2\)</span> est évidemment <span class="math display">\[ \tilde{\sigma}^2_n = \frac{1}{n}\sum_{i=1}^n (X_i - \mu)^2.\]</span> Comme les <span class="math inline">\((X_i - \mu)/\sigma\)</span> sont des variables aléatoires gaussiennes centrées réduites, l’estimateur <span class="math inline">\(\tilde{\sigma}^2_n \times (n/ \sigma^2)\)</span> est une somme de <span class="math inline">\(n\)</span> gaussiennes standard indépendantes. La loi de cette statistique est connue :&nbsp;c’est une <a href="https://fr.wikipedia.org/wiki/Loi_du_%CF%87%C2%B2">loi du chi-deux</a> à <span class="math inline">\(n\)</span> paramètres de liberté. Cette loi n’est pas symétrique, puisqu’elle est supportée sur <span class="math inline">\([0,\infty[\)</span>. On note souvent <span class="math inline">\(k^-_{n,\alpha}\)</span> et <span class="math inline">\(k^+_{n,\alpha}\)</span> les nombres les plus éloignées possible (ils exisent) tels que <span class="math inline">\(\mathbb{P}(k^-_{n,\alpha}&lt; \chi^2(n)&lt;k^+_{n,\alpha}) = 1-\alpha\)</span>. Ainsi, <span class="math display">\[P_{\sigma^2}(k^-_{n,\alpha}&lt; \frac{n \tilde{\sigma}^2_n}{\sigma^2} &lt; k^+_{n,\alpha}) = \alpha.\]</span> En pivotant comme dans les exemples précédents, on obtient que l’intervalle <span class="math display">\[\left[\frac{n\tilde{\sigma}_n^2}{k^{+}_{n,\alpha}} ~~;~~ \frac{n\tilde{\sigma}_n^2}{k^-_{n,\alpha}} \right] \]</span> est un intervalle de confiance de niveau <span class="math inline">\(\alpha\)</span> pour <span class="math inline">\(\sigma^2\)</span>.</p>
<p><strong>Lorsque <span class="math inline">\(\mu\)</span> est inconnue.</strong></p>
<p>Cette fois, on utilise l’estimateur déjà évoqué plus tôt, à savoir <span class="math display">\[ \hat{\sigma}_n^2 = \frac{1}{n-1}\sum_{i=1}^n (X_i - \bar{X}_n)^2.\]</span> La loi de <span class="math inline">\((n-1)\hat{\sigma}^2_n / \sigma^2\)</span> est encore une loi du chi-deux, mais à <span class="math inline">\(n-1\)</span> paramètres de liberté. Ainsi, le même raisonnement que ci-dessus donne l’intervalle de confiance de niveau <span class="math inline">\(\alpha\)</span> suivant :&nbsp; <span class="math display">\[\left[\frac{(n-1)\tilde{\sigma}_n^2}{k^+_{n-1,\alpha}} ~~;~~ \frac{(n-1)\tilde{\sigma}_n^2}{k^-_{n-1,\alpha}} \right]. \]</span></p>
</section>
</section>
<section id="exemples-asymptotiques" class="level2" data-number="4.3">
<h2 data-number="4.3" class="anchored" data-anchor-id="exemples-asymptotiques"><span class="header-section-number">4.3</span> Exemples asymptotiques</h2>
<ul>
<li>Estimation du paramètre <span class="math inline">\(p\)</span> dans un modèle de Bernoulli.</li>
<li>Estimation de moyenne dans un modèle non-gaussien.</li>
</ul>
</section>
<section id="outils-pour-construire-des-intervalles-de-confiance" class="level2" data-number="4.4">
<h2 data-number="4.4" class="anchored" data-anchor-id="outils-pour-construire-des-intervalles-de-confiance"><span class="header-section-number">4.4</span> Outils pour construire des intervalles de confiance</h2>
<section id="quantiles" class="level3" data-number="4.4.1">
<h3 data-number="4.4.1" class="anchored" data-anchor-id="quantiles"><span class="header-section-number">4.4.1</span> Quantiles</h3>
<p>Si <span class="math inline">\(X\)</span> est une variable aléatoire sur <span class="math inline">\(\mathbb{R}\)</span>, un quantile d’ordre <span class="math inline">\(\alpha \in ]0,1[\)</span>, noté <span class="math inline">\(q_\alpha\)</span>, est un nombre tel que <span class="math inline">\(\mathbb{P}(X \leqslant q_\alpha) = \alpha\)</span>. Lorsque <span class="math inline">\(X\)</span> est continue, un tel nombre existe forcément, car la fonction de répartition <span class="math inline">\(F(x) = \mathbb{P}(X\leqslant x)\)</span> est une surjection continue. Les quantiles symétriques <span class="math inline">\(z_\alpha\)</span> sont, eux, définis par <span class="math inline">\(\mathbb{P}(|X|\leqslant z_\alpha) = \alpha\)</span>.</p>
<p>Si la loi de <span class="math inline">\(X\)</span> est de surcroît symétrique, les quantiles symétriques s’expriment facilement en fonction des quantiles classiques. En effet, <span class="math inline">\(\mathbb{P}(|X|\leqslant z)\)</span> est égal à <span class="math inline">\(\mathbb{P}(X \leqslant z) - \mathbb{P}(X \leqslant -z)\)</span>. Or, si la loi de <span class="math inline">\(X\)</span> est symétrique, alors <span class="math inline">\(\mathbb{P}(X \leqslant -z) = 1 - \mathbb{P}(X \leqslant z)\)</span>, et donc <span class="math display">\[ \mathbb{P}(|X|\leqslant z) = 2\mathbb{P}(X \leqslant z) - 1.\]</span> Il suffit alors de choisir pour <span class="math inline">\(z\)</span> le quantile <span class="math inline">\(q_{\frac{1+\alpha}{2}}\)</span> pour obtenir <span class="math inline">\(\mathbb{P}(|X|\leqslant z) = \alpha\)</span>.</p>
<p>En règle générale, les quantiles s’obtiennent en inversant la fonction de répartition :&nbsp;lorsque celle-ci est une bijection sur <span class="math inline">\(]0,1[\)</span>, alors <span class="math inline">\(q_\alpha = F^{-1}(\alpha)\)</span>. En règle générale, il n’y a pas de forme fermée. Par exemple, pour une loi gaussienne standard, <span class="math display">\[F(x) = \frac{1}{\sqrt{2\pi}}\int_{-\infty}^x e^{-u^2/2}du\]</span> qui elle-même n’a pas d’écriture plus simple. Fort heureusement, les outils de calcul numérique permettent d’effectuer ces calculs avec une grande précision. La table suivante donne les quantiles symétriques de la gaussienne.</p>
<table class="table">
<thead>
<tr class="header">
<th><span class="math inline">\(\alpha\)</span></th>
<th>90%</th>
<th>95%</th>
<th>98%</th>
<th>99%</th>
<th>99.9%</th>
<th>99.99999%</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><span class="math inline">\(z_\alpha\)</span></td>
<td>1.64</td>
<td>1.96</td>
<td>2.32</td>
<td>2.57</td>
<td>3.2</td>
<td>5.32</td>
</tr>
</tbody>
</table>
<div id="thm-gaussiantail" class="theorem">
<p><span class="theorem-title"><strong>Théorème 4.2 (Queues de distribution de la gaussienne) </strong></span>Si <span class="math inline">\(x\)</span> est plus grand que 1, <span class="math display">\[  \left(\frac{1}{x} - \frac{1}{x^3}\right) \frac{e^{-x^2/2}}{\sqrt{2\pi}}\leqslant \mathbb{P}(X &gt; x) \leqslant \frac{1}{x}\frac{e^{-x^2/2}}{\sqrt{2\pi}} \]</span> En particulier, si <span class="math inline">\(x\)</span> est grand, <span class="math inline">\(\mathbb{P}(X \geqslant x) \sim e^{-x^2/2}/x\sqrt{2\pi}\)</span> avec une erreur d’ordre <span class="math inline">\(O(e^{-x^2/2}/x^3)\)</span>.</p>
</div>
<p>À titre d’exemple, pour <span class="math inline">\(x=2.32\)</span> cette approximation donne 98.83%, ce qui est remarquablement proche de 98%. Pour <span class="math inline">\(x = 2.57\)</span> on trouve 99.42%.</p>
<div class="proof">
<p><span class="proof-title"><em>Preuve</em>. </span>À écrire.</p>
</div>
</section>
<section id="inégalités-de-concentration" class="level3" data-number="4.4.2">
<h3 data-number="4.4.2" class="anchored" data-anchor-id="inégalités-de-concentration"><span class="header-section-number">4.4.2</span> Inégalités de concentration</h3>
<p>Les outils de base pour construire des intervalles de confiance sont les inégalités de concentration. Une inégalité de concentration pour une variable aléatoire intégrable <span class="math inline">\(X\)</span> est une inégalité de type <span class="math display">\[\mathbb{P}(|X - \mathbb{E}[X]|&gt;x) \leqslant \text{(quelque chose de petit quand x est grand)}, \]</span> c’est-à-dire une inégalité qui contrôle la probabilité pour que les réalisations d’une variable aléatoire <span class="math inline">\(X\)</span> soient éloignées de leur valeur moyenne.</p>
<div id="thm-bt" class="theorem">
<p><span class="theorem-title"><strong>Théorème 4.3 </strong></span>Soit <span class="math inline">\(X\)</span> une variable aléatoire de carré intégrable. Alors, <span class="math display">\[ \mathbb{P}(|X - \mathbb{E}[X]|\geqslant x)\leqslant \frac{\mathrm{Var}(X)}{x^2}.\]</span></p>
</div>
<div class="proof">
<p><span class="proof-title"><em>Preuve</em>. </span>Élever au carré les deux membres de l’inégalité, puis appliquer l’inégalité de Markov à la variable aléatoire positive <span class="math inline">\(|X - \mathbb{E}X|^2\)</span> dont l’espérance est <span class="math inline">\(\mathrm{Var}(X)\)</span>.</p>
</div>
<div id="thm-hoeffding" class="theorem">
<p><span class="theorem-title"><strong>Théorème 4.4 (Inégalité de Hoeffding) </strong></span>Soient <span class="math inline">\(X_1, \dotsc, X_n\)</span> des variables aléatoires indépendantes, pas forcément de même loi. On suppose que chaque <span class="math inline">\(X_i\)</span> est à valeurs dans un intervalle borné <span class="math inline">\([a_i, b_i]\)</span> et on pose <span class="math inline">\(S_n = X_1 + \dotsc + X_n\)</span>.</p>
<p><span class="math display">\[\mathbb{P}(S_n - \mathbb{E}[S_n] \geqslant x) \leqslant e^{-\frac{2x^2}{\sum_{i=1}^n}(b_i - a_i)^2}.\]</span></p>
</div>
<div class="proof">
<p><span class="proof-title"><em>Preuve</em>. </span>À écrire.</p>
</div>


</section>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const disableStylesheet = (stylesheets) => {
    for (let i=0; i < stylesheets.length; i++) {
      const stylesheet = stylesheets[i];
      stylesheet.rel = 'prefetch';
    }
  }
  const enableStylesheet = (stylesheets) => {
    for (let i=0; i < stylesheets.length; i++) {
      const stylesheet = stylesheets[i];
      stylesheet.rel = 'stylesheet';
    }
  }
  const manageTransitions = (selector, allowTransitions) => {
    const els = window.document.querySelectorAll(selector);
    for (let i=0; i < els.length; i++) {
      const el = els[i];
      if (allowTransitions) {
        el.classList.remove('notransition');
      } else {
        el.classList.add('notransition');
      }
    }
  }
  const toggleColorMode = (alternate) => {
    // Switch the stylesheets
    const alternateStylesheets = window.document.querySelectorAll('link.quarto-color-scheme.quarto-color-alternate');
    manageTransitions('#quarto-margin-sidebar .nav-link', false);
    if (alternate) {
      enableStylesheet(alternateStylesheets);
      for (const sheetNode of alternateStylesheets) {
        if (sheetNode.id === "quarto-bootstrap") {
          toggleBodyColorMode(sheetNode);
        }
      }
    } else {
      disableStylesheet(alternateStylesheets);
      toggleBodyColorPrimary();
    }
    manageTransitions('#quarto-margin-sidebar .nav-link', true);
    // Switch the toggles
    const toggles = window.document.querySelectorAll('.quarto-color-scheme-toggle');
    for (let i=0; i < toggles.length; i++) {
      const toggle = toggles[i];
      if (toggle) {
        if (alternate) {
          toggle.classList.add("alternate");     
        } else {
          toggle.classList.remove("alternate");
        }
      }
    }
    // Hack to workaround the fact that safari doesn't
    // properly recolor the scrollbar when toggling (#1455)
    if (navigator.userAgent.indexOf('Safari') > 0 && navigator.userAgent.indexOf('Chrome') == -1) {
      manageTransitions("body", false);
      window.scrollTo(0, 1);
      setTimeout(() => {
        window.scrollTo(0, 0);
        manageTransitions("body", true);
      }, 40);  
    }
  }
  const isFileUrl = () => { 
    return window.location.protocol === 'file:';
  }
  const hasAlternateSentinel = () => {  
    let styleSentinel = getColorSchemeSentinel();
    if (styleSentinel !== null) {
      return styleSentinel === "alternate";
    } else {
      return false;
    }
  }
  const setStyleSentinel = (alternate) => {
    const value = alternate ? "alternate" : "default";
    if (!isFileUrl()) {
      window.localStorage.setItem("quarto-color-scheme", value);
    } else {
      localAlternateSentinel = value;
    }
  }
  const getColorSchemeSentinel = () => {
    if (!isFileUrl()) {
      const storageValue = window.localStorage.getItem("quarto-color-scheme");
      return storageValue != null ? storageValue : localAlternateSentinel;
    } else {
      return localAlternateSentinel;
    }
  }
  let localAlternateSentinel = 'default';
  // Dark / light mode switch
  window.quartoToggleColorScheme = () => {
    // Read the current dark / light value 
    let toAlternate = !hasAlternateSentinel();
    toggleColorMode(toAlternate);
    setStyleSentinel(toAlternate);
  };
  // Ensure there is a toggle, if there isn't float one in the top right
  if (window.document.querySelector('.quarto-color-scheme-toggle') === null) {
    const a = window.document.createElement('a');
    a.classList.add('top-right');
    a.classList.add('quarto-color-scheme-toggle');
    a.href = "";
    a.onclick = function() { try { window.quartoToggleColorScheme(); } catch {} return false; };
    const i = window.document.createElement("i");
    i.classList.add('bi');
    a.appendChild(i);
    window.document.body.appendChild(a);
  }
  // Switch to dark mode if need be
  if (hasAlternateSentinel()) {
    toggleColorMode(true);
  } else {
    toggleColorMode(false);
  }
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copié");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copié");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="./ch2_ex.html" class="pagination-link">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Exercices</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="./ch4.html" class="pagination-link">
        <span class="nav-page-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Test d’hypothèse</span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->



</body></html>